
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: app

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples: debug
server:
  port: 8081
  context-path: /
